"""empty message

Revision ID: 4ef0867b56a8
Revises: 8fb3eb776bf1
Create Date: 2021-12-31 07:49:59.822875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef0867b56a8'
down_revision = '8fb3eb776bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('answer', 'contemt')
    op.add_column('question', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('question', 'contemt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('contemt', sa.TEXT(), nullable=False))
    op.drop_column('question', 'content')
    op.add_column('answer', sa.Column('contemt', sa.TEXT(), nullable=False))
    op.drop_column('answer', 'content')
    # ### end Alembic commands ###
